name: "Run tests"

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    # cgroup version shouldn't be cgroup2fs
    - name: Debug
      run: |
        env
        [[ $(stat -c %T -f /sys/fs/cgroup) != "cgroup2fs" ]] 

    - name: Set Up Git repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v2

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    # test every scenario with test_sequence from ../../molecule/default/molecule.yml
    - name: Run tests
      run: |
        molecule lint
        molecule test --all
